//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEmployees.Models
{
    using System;
    
    public partial class Employee
    {
        public string Status { get; set; }
        public string Department { get; set; }
        public string Position { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateEmploy { get; set; }
        public System.DateTime DateUnemploy { get; set; }
    }
}
